version: '3'
services:
  calculator:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
       - "6379:6379"     